# Generated by Django 4.2.1 on 2023-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='prod_date',
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='', max_length=255, verbose_name='Author Name'),
            preserve_default=False,
        ),
    ]
